.TH man 1 "12 Jan 2013" "0.5" "Qrest"
.SH NOM
qrest \- Qrest Really Easy Studio Toolkit
.SH SYNOPSIS
qrest
.SH DESCRIPTION
.B qrest
aide à calculer les temps de délai et les fréquences de LFO en fonction du tempo.
.P
Il y a 2 façons d'entrer les valeurs de tempo :
.IP \(bu 2
Entrée numérique au clavier : l'utilisateur entre simplement la valeur de tempo dans un champ de texte et appuie sur \'entrée\'.
.IP \(bu 2
Clic au bouton en temps-réel : l'utilisateur clique sur un bouton en synchronisation avec des temps forts, et qrest lui indiquera s'il tape régulièrement.
.P
Les résultats sont affichés pour toutes les notes comprises entre une ronde et une triple-croche, et un ensemble de boutons-radio permet à l'utilisateur de choisir entre des notes normales, pointées, et des triolets.
.SH OPTIONS
Il n'y a actuellement aucune option utilisée.
.SH BOGUES
Pas de bogue connu pour le moment.
.SH REMONTER LES BOGUES
Utiliser note système de suivi de bogue à http://requests.wardsback.org/browse/QREST
.SH AUTEUR
.nf
Frédéric "deufrai" CORNU (fcornu@wardsback.org)
.fi
.SH COPYRIGHT
Copyright \(co 2008-2012 Frederic CORNU.
.br
Licence : GPLv3. see http://www.gnu.org/licenses/gpl-3.0.txt
