.TH man 1 "20 November 2008" "0.4" "Qrest"
.SH NAME
qrest \- Qrest Really Easy Studio Toolkit
.SH SYNOPSIS
qrest
.SH DESCRIPTION
.B qrest
helps with calculating delay times and LFO frequencies according to tempo. 
.P
There are 2 ways to entered the tempo value :
.IP \(bu 2
Keyboard numerical input : User simply types tempo value in a text field end hit \'enter\'.
.IP \(bu 2
Realtime button click : User clicks a button in sync with beats, and qrest will tell her if she taps steadily.
.P
Results are displayed for all notes from a whole to a thirtysecond, and a set of radio-buttons permits user to choose from plain, dotted and triplet notes.
.SH OPTIONS
There are currently no option used.
.SH BUGS
No known bugs at this time. 
.SH REPORTING BUGS
Use our bugtracking system at http://bugs.qrest.org
.SH AUTHOR
.nf
Frederic "deufrai" CORNU (fcornu@qrest.org)
.fi
