.\" A sample man page. 
.\" Contact admin@yourcompany.com to correct errors or omissions. 
.TH man 1 "7 November 2008" "0.3" "Zest"
.SH NAME
zest \- Zest Easy Studio Toolkit
.SH SYNOPSIS
zest
.SH DESCRIPTION
.B zest
helps you with calculating delay times and LFO frequencies according to tempo. It also have a "taptempo" freature allowing you to click the "TAP" button to set the tempo.
.SH OPTIONS
There are currently no option used.
.SH BUGS
No known bugs at this time. 
.SH AUTHOR
.nf
Frédéric "deufrai" CORNU (fcornu@wardsback.org)
.fi
