Zest Easy Studio Toolkit: DelayCalculator Class Reference
DelayCalculator Class Reference
#include <delayCalculator.h>
Detailed Description
Processor that calculates delay values according to app data stored tempo value.
Definition at line 29 of file delayCalculator.h.
Public Member Functions
virtual void process (void)
Get tempo from app data store and calculate delays.
Static Public Member Functions
static DelayCalculator * getInstance ()
init and get the only instance.
static void destroy (void)
destroy the only instance.
Private Member Functions
DelayCalculator ()
virtual ~DelayCalculator ()
const double getDelayPeriodFromTempoAndMutliplier (const double tempo, const double mutliplier)
Static Private Attributes
static DelayCalculator * _instance = 0
The only instance.
Constructor & Destructor Documentation
DelayCalculator::DelayCalculator () [private]
Definition at line 32 of file delayCalculator.cpp.
Referenced by getInstance().
DelayCalculator::~DelayCalculator () [private, virtual]
Definition at line 38 of file delayCalculator.cpp.
Member Function Documentation
DelayCalculator * DelayCalculator::getInstance (void) [static]
init and get the only instance.
Returns:
the instance
Definition at line 43 of file delayCalculator.cpp.
References _instance, and DelayCalculator().
Referenced by Document::updateDelays().
void DelayCalculator::destroy (void) [static]
destroy the only instance.
Definition at line 56 of file delayCalculator.cpp.
References _instance.
Referenced by Document::~Document().
void DelayCalculator::process (void) [virtual]
Get tempo from app data store and calculate delays.
Implements Processor.
Definition at line 72 of file delayCalculator.cpp.
References getDelayPeriodFromTempoAndMutliplier(), Document::getEighthDelay(), Document::getHalfDelay(), Document::getInstance(), Document::getMultiplier(), Document::getQuarterDelay(), Document::getSixTeenthDelay(), Document::getTempo(), Document::getThirtySecondDelay(), Document::getWholeDelay(), and Delay::setPeriod().
Referenced by Document::updateDelays().
const double DelayCalculator::getDelayPeriodFromTempoAndMutliplier (const double tempo, const double mutliplier) [private]
Definition at line 164 of file delayCalculator.cpp.
References Constants::MILLISEC_PER_SECOND, and Constants::SECONDS_PER_MINUTE.
Referenced by process().
Member Data Documentation
DelayCalculator * DelayCalculator::_instance = 0 [static, private]
The only instance.
Definition at line 43 of file delayCalculator.h.
Referenced by destroy(), and getInstance().
The documentation for this class was generated from the following files:
src/process/delayCalculator.h
src/process/delayCalculator.cpp