Zest Easy Studio Toolkit: ZestMainWindow Class Reference
ZestMainWindow Class Reference
#include <zestmainwindow.h>
Detailed Description
Zest Easy Studio Toolkit main window.
Definition at line 32 of file zestmainwindow.h.
Public Member Functions
ZestMainWindow (QWidget *parent=0)
~ZestMainWindow ()
virtual void updateView ()
update view to reflect App data changes
Private Slots
void on_tempoEdit_returnPressed ()
Slot that gets called when 'return' is presses with tempo edit field focused.
void on_tapButton_pressed ()
Slot that gets called when 'tap' button is pressed.
void on_plainRadio_clicked ()
Slot that gets called when 'plain' radio button is clicked.
void on_dottedRadio_clicked ()
Slot that gets called when 'dotted' radio button is clicked.
void on_tripletRadio_clicked ()
Slot that gets called when 'triplet' radio button is clicked.
void on_actionQuit_triggered ()
Slot that gets called upon "Quit" action triggering.
void on_actionAbout_triggered ()
Slot that gets called upon "About" action triggering.
Private Member Functions
virtual bool eventFilter (QObject *target, QEvent *event)
Custom event handler used for tempo edit field and mousewheel events.
void setFocusToTempoInput (void) const
Give the focus to tempo input field.
void processTempoInput (void) const
pass tempo input field content value to app data
void statusPermMessage (const QString &message) const
Display a permanent message in status bar.
void statusTempMessage (const QString &message) const
Display a temporary message in status bar.
Private Attributes
Ui::ZestMainWindowClass ui
The GUI subclass.
Document * _document
Application data store.
Constructor & Destructor Documentation
ZestMainWindow::ZestMainWindow (QWidget * parent = 0)
Definition at line 36 of file zestmainwindow.cpp.
References _document, processTempoInput(), Observable::registerObserver(), setFocusToTempoInput(), statusTempMessage(), ui, and updateView().
ZestMainWindow::~ZestMainWindow ()
Definition at line 65 of file zestmainwindow.cpp.
Member Function Documentation
void ZestMainWindow::updateView (void) [virtual]
update view to reflect App data changes
Implements Observer.
Definition at line 77 of file zestmainwindow.cpp.
References _document, Document::getEighthDelay(), Delay::getFrenquency(), Document::getHalfDelay(), Delay::getPeriod(), Document::getQuarterDelay(), Document::getSixTeenthDelay(), Document::getTempo(), Document::getThirtySecondDelay(), Document::getWholeDelay(), Document::isSteady(), Document::isTempoFromTap(), statusPermMessage(), and ui.
Referenced by ZestMainWindow().
void ZestMainWindow::on_tempoEdit_returnPressed () [private, slot]
Slot that gets called when 'return' is presses with tempo edit field focused.
Definition at line 176 of file zestmainwindow.cpp.
References processTempoInput(), and setFocusToTempoInput().
void ZestMainWindow::on_tapButton_pressed () [private, slot]
Slot that gets called when 'tap' button is pressed.
Definition at line 187 of file zestmainwindow.cpp.
References TapTempoCalculator::getInstance(), and TapTempoCalculator::process().
void ZestMainWindow::on_plainRadio_clicked () [private, slot]
Slot that gets called when 'plain' radio button is clicked.
Definition at line 195 of file zestmainwindow.cpp.
References Document::getInstance(), Document::MULTIPLIER_PLAIN, and Document::setMultiplier().
void ZestMainWindow::on_dottedRadio_clicked () [private, slot]
Slot that gets called when 'dotted' radio button is clicked.
Definition at line 203 of file zestmainwindow.cpp.
References Document::getInstance(), Document::MULTIPLIER_DOTTED, and Document::setMultiplier().
void ZestMainWindow::on_tripletRadio_clicked () [private, slot]
Slot that gets called when 'triplet' radio button is clicked.
Definition at line 211 of file zestmainwindow.cpp.
References Document::getInstance(), Document::MULTIPLIER_TRIPLET, and Document::setMultiplier().
void ZestMainWindow::on_actionQuit_triggered () [private, slot]
Slot that gets called upon "Quit" action triggering.
Definition at line 220 of file zestmainwindow.cpp.
void ZestMainWindow::on_actionAbout_triggered () [private, slot]
Slot that gets called upon "About" action triggering.
Definition at line 228 of file zestmainwindow.cpp.
References Constants::VERSION_STRING.
bool ZestMainWindow::eventFilter (QObject * target, QEvent * event) [private, virtual]
Custom event handler used for tempo edit field and mousewheel events.
Parameters:
target the object tagetted by the event
event the event to be handled
Returns:
true if event should not be handled by other handlers.
Definition at line 245 of file zestmainwindow.cpp.
References processTempoInput(), and ui.
void ZestMainWindow::setFocusToTempoInput (void) const [private]
Give the focus to tempo input field.
Definition at line 279 of file zestmainwindow.cpp.
References ui.
Referenced by on_tempoEdit_returnPressed(), and ZestMainWindow().
void ZestMainWindow::processTempoInput (void) const [private]
pass tempo input field content value to app data
Definition at line 288 of file zestmainwindow.cpp.
References _document, Document::setTempo(), Document::setTempoFromTap(), and ui.
Referenced by eventFilter(), on_tempoEdit_returnPressed(), and ZestMainWindow().
void ZestMainWindow::statusPermMessage (const QString & message) const [private]
Display a permanent message in status bar.
Parameters:
message the message to display
Definition at line 300 of file zestmainwindow.cpp.
References ui.
Referenced by updateView().
void ZestMainWindow::statusTempMessage (const QString & message) const [private]
Display a temporary message in status bar.
Parameters:
message the message to display
Definition at line 308 of file zestmainwindow.cpp.
References ui.
Referenced by ZestMainWindow().
Member Data Documentation
Ui::ZestMainWindowClass ZestMainWindow::ui [private]
The GUI subclass.
Definition at line 132 of file zestmainwindow.h.
Referenced by eventFilter(), processTempoInput(), setFocusToTempoInput(), statusPermMessage(), statusTempMessage(), updateView(), and ZestMainWindow().
Document* ZestMainWindow::_document [private]
Application data store.
Definition at line 135 of file zestmainwindow.h.
Referenced by processTempoInput(), updateView(), and ZestMainWindow().
The documentation for this class was generated from the following files:
src/gui/widgets/zestmainwindow.h
src/gui/widgets/zestmainwindow.cpp