Zest Easy Studio Toolkit: Document Class Reference
Document Class Reference
#include <document.h>
Detailed Description
Stores all application data.
Singelton class that stores all application data. Implements the Observable interface
Definition at line 33 of file document.h.
Public Member Functions
void setTempo (const double tempo)
Set the tempo.
const double getTempo (void) const
Get the tempo.
const bool isTempoFromTap (void) const
Get tempoFromTap flag.
void setTempoFromTap (const bool tempoFromTap)
Set tempoFromTap flag.
const double getMultiplier (void) const
Get multiplier.
void setMultiplier (const double multi)
Set the multiplier.
const bool isSteady (void) const
Get steadiness flag.
void setSteady (const bool steady)
Set steadiness flag.
Delay * getWholeDelay () const
Get the delay object for a whole note.
Delay * getHalfDelay () const
Get the delay object for a half note.
Delay * getQuarterDelay () const
Get the delay object for a quarter note.
Delay * getEighthDelay () const
Get the delay object for a eighth note.
Delay * getSixTeenthDelay () const
Get the delay object for a sixteenth note.
Delay * getThirtySecondDelay () const
Get the delay object for a thirtysecond note.
Static Public Member Functions
static Document * getInstance ()
get the singleton instance.
static void destroy ()
Destroy the singleton instance.
Static Public Attributes
static const double MULTIPLIER_PLAIN = 1.0
Mutlilpier for plain notes.
static const double MULTIPLIER_DOTTED = 1.5
Multiplier for dotted notes.
static const double MULTIPLIER_TRIPLET = 2.0 / 3.0
Mutliplier for triplet notes.
Private Member Functions
Document ()
virtual ~Document ()
void initDelays (void)
Init vector of Delays.
void destroyDelays (void)
destroy vector of delays
void updateDelays (void)
Ask for the delay calculation.
Private Attributes
double _tempo
The tempo.
vector< Delay * > _delays
vector of Delay objects
bool _steady
has tempo been tapped steadily ?
bool _tempoFromTap
does tempo value come from taptempo ?
double _multiplier
The multiplier used for plain, dotted and triplet notes.
Static Private Attributes
static Document * _instance = 0
The single instance.
static const int WHOLE = 0
static const int HALF = 1
static const int QUARTER = 2
static const int EIGHTH = 3
static const int SIXTEENTH = 4
static const int THIRTYSECOND = 5
static const int DELAYS_COUNT = 6
static const double TEMPO_DEFAULT = 60.0
Default tempo for app startup.
static const double TEMPO_MIN = 1.0
Minimum allowed tempo as input.
static const double TEMPO_MAX = 999.0
Maximum allowed tempo as input.
Constructor & Destructor Documentation
Document::Document () [private]
Definition at line 32 of file document.cpp.
References initDelays().
Referenced by getInstance().
Document::~Document () [private, virtual]
Definition at line 46 of file document.cpp.
References DelayCalculator::destroy(), and destroyDelays().
Member Function Documentation
Document * Document::getInstance () [static]
get the singleton instance.
Returns:
the instance
Definition at line 58 of file document.cpp.
References _instance, and Document().
Referenced by main(), ZestMainWindow::on_dottedRadio_clicked(), ZestMainWindow::on_plainRadio_clicked(), ZestMainWindow::on_tripletRadio_clicked(), TapTempoCalculator::process(), and DelayCalculator::process().
void Document::destroy () [static]
Destroy the singleton instance.
Definition at line 71 of file document.cpp.
References _instance.
Referenced by main().
void Document::setTempo (const double tempo)
Set the tempo.
Parameters:
tempo the tempo to be set
Definition at line 89 of file document.cpp.
References _tempo, Observable::notifyObservers(), TEMPO_MAX, TEMPO_MIN, and updateDelays().
Referenced by TapTempoCalculator::process(), and ZestMainWindow::processTempoInput().
const double Document::getTempo (void) const [inline]
Get the tempo.
Returns:
the tempo
Definition at line 71 of file document.h.
References _tempo.
Referenced by DelayCalculator::process(), and ZestMainWindow::updateView().
const bool Document::isTempoFromTap (void) const [inline]
Get tempoFromTap flag.
Returns:
tempoFromTap flag
Definition at line 78 of file document.h.
References _tempoFromTap.
Referenced by ZestMainWindow::updateView().
void Document::setTempoFromTap (const bool tempoFromTap) [inline]
Set tempoFromTap flag.
Parameters:
tempoFromTap to set
Definition at line 85 of file document.h.
References _tempoFromTap.
Referenced by TapTempoCalculator::process(), and ZestMainWindow::processTempoInput().
const double Document::getMultiplier (void) const [inline]
Get multiplier.
Returns:
the multiplier
Definition at line 94 of file document.h.
References _multiplier.
Referenced by DelayCalculator::process().
void Document::setMultiplier (const double multi) [inline]
Set the multiplier.
Parameters:
multi the multiplier
Definition at line 104 of file document.h.
References _multiplier, Observable::notifyObservers(), and updateDelays().
Referenced by ZestMainWindow::on_dottedRadio_clicked(), ZestMainWindow::on_plainRadio_clicked(), and ZestMainWindow::on_tripletRadio_clicked().
const bool Document::isSteady (void) const [inline]
Get steadiness flag.
Returns:
steadiness flag
Definition at line 116 of file document.h.
References _steady.
Referenced by ZestMainWindow::updateView().
void Document::setSteady (const bool steady) [inline]
Set steadiness flag.
Parameters:
steady steadiness flag value
Definition at line 123 of file document.h.
References _steady.
Referenced by TapTempoCalculator::process().
Delay* Document::getWholeDelay () const [inline]
Get the delay object for a whole note.
Returns:
the 'whole' delay
Definition at line 130 of file document.h.
References _delays, and WHOLE.
Referenced by DelayCalculator::process(), and ZestMainWindow::updateView().
Delay* Document::getHalfDelay () const [inline]
Get the delay object for a half note.
Returns:
the 'half' delay
Definition at line 137 of file document.h.
References _delays, and HALF.
Referenced by DelayCalculator::process(), and ZestMainWindow::updateView().
Delay* Document::getQuarterDelay () const [inline]
Get the delay object for a quarter note.
Returns:
the 'quarter' delay
Definition at line 144 of file document.h.
References _delays, and QUARTER.
Referenced by DelayCalculator::process(), and ZestMainWindow::updateView().
Delay* Document::getEighthDelay () const [inline]
Get the delay object for a eighth note.
Returns:
the 'eighth' delay
Definition at line 151 of file document.h.
References _delays, and EIGHTH.
Referenced by DelayCalculator::process(), and ZestMainWindow::updateView().
Delay* Document::getSixTeenthDelay () const [inline]
Get the delay object for a sixteenth note.
Returns:
the 'sixteenth' delay
Definition at line 158 of file document.h.
References _delays, and SIXTEENTH.
Referenced by DelayCalculator::process(), and ZestMainWindow::updateView().
Delay* Document::getThirtySecondDelay () const [inline]
Get the delay object for a thirtysecond note.
Returns:
the 'thirtysecond' delay
Definition at line 165 of file document.h.
References _delays, and THIRTYSECOND.
Referenced by DelayCalculator::process(), and ZestMainWindow::updateView().
void Document::initDelays (void) [private]
Init vector of Delays.
Definition at line 108 of file document.cpp.
References _delays, and DELAYS_COUNT.
Referenced by Document().
void Document::destroyDelays (void) [private]
destroy vector of delays
Definition at line 116 of file document.cpp.
References _delays, and DELAYS_COUNT.
Referenced by ~Document().
void Document::updateDelays (void) [private]
Ask for the delay calculation.
Definition at line 129 of file document.cpp.
References DelayCalculator::getInstance(), and DelayCalculator::process().
Referenced by setMultiplier(), and setTempo().
Member Data Documentation
Document * Document::_instance = 0 [static, private]
The single instance.
Definition at line 172 of file document.h.
Referenced by destroy(), and getInstance().
const int Document::WHOLE = 0 [static, private]
Definition at line 178 of file document.h.
Referenced by getWholeDelay().
const int Document::HALF = 1 [static, private]
Definition at line 179 of file document.h.
Referenced by getHalfDelay().
const int Document::QUARTER = 2 [static, private]
Definition at line 180 of file document.h.
Referenced by getQuarterDelay().
const int Document::EIGHTH = 3 [static, private]
Definition at line 181 of file document.h.
Referenced by getEighthDelay().
const int Document::SIXTEENTH = 4 [static, private]
Definition at line 182 of file document.h.
Referenced by getSixTeenthDelay().
const int Document::THIRTYSECOND = 5 [static, private]
Definition at line 183 of file document.h.
Referenced by getThirtySecondDelay().
const int Document::DELAYS_COUNT = 6 [static, private]
Definition at line 184 of file document.h.
Referenced by destroyDelays(), and initDelays().
const double Document::TEMPO_DEFAULT = 60.0 [static, private]
Default tempo for app startup.
Definition at line 190 of file document.h.
const double Document::TEMPO_MIN = 1.0 [static, private]
Minimum allowed tempo as input.
Definition at line 192 of file document.h.
Referenced by setTempo().
const double Document::TEMPO_MAX = 999.0 [static, private]
Maximum allowed tempo as input.
Definition at line 194 of file document.h.
Referenced by setTempo().
const double Document::MULTIPLIER_PLAIN = 1.0 [static]
Mutlilpier for plain notes.
Definition at line 201 of file document.h.
Referenced by ZestMainWindow::on_plainRadio_clicked().
const double Document::MULTIPLIER_DOTTED = 1.5 [static]
Multiplier for dotted notes.
Definition at line 204 of file document.h.
Referenced by ZestMainWindow::on_dottedRadio_clicked().
const double Document::MULTIPLIER_TRIPLET = 2.0 / 3.0 [static]
Mutliplier for triplet notes.
Definition at line 207 of file document.h.
Referenced by ZestMainWindow::on_tripletRadio_clicked().
double Document::_tempo [private]
The tempo.
Definition at line 214 of file document.h.
Referenced by getTempo(), and setTempo().
vector<Delay*> Document::_delays [private]
vector of Delay objects
Definition at line 217 of file document.h.
Referenced by destroyDelays(), getEighthDelay(), getHalfDelay(), getQuarterDelay(), getSixTeenthDelay(), getThirtySecondDelay(), getWholeDelay(), and initDelays().
bool Document::_steady [private]
has tempo been tapped steadily ?
Definition at line 220 of file document.h.
Referenced by isSteady(), and setSteady().
bool Document::_tempoFromTap [private]
does tempo value come from taptempo ?
Definition at line 223 of file document.h.
Referenced by isTempoFromTap(), and setTempoFromTap().
double Document::_multiplier [private]
The multiplier used for plain, dotted and triplet notes.
Definition at line 226 of file document.h.
Referenced by getMultiplier(), and setMultiplier().
The documentation for this class was generated from the following files:
src/model/document.h
src/model/document.cpp