Zest Easy Studio Toolkit: Delay Class Reference
Delay Class Reference
#include <delay.h>
Detailed Description
Represents a delay for which we want to display two values.
The period in milliseconds
The frequency of an LFO beating at that period
Definition at line 32 of file delay.h.
Public Member Functions
Delay ()
virtual ~Delay ()
void setPeriod (const double period)
Set the period.
const double getPeriod () const
Get the period.
const double getFrenquency () const
Get the frenquency.
Private Attributes
double _period
the period of this delay
double _frequency
the frequency corresponding to the period of this delay
Constructor & Destructor Documentation
Delay::Delay ()
Definition at line 28 of file delay.cpp.
Delay::~Delay () [virtual]
Definition at line 35 of file delay.cpp.
Member Function Documentation
void Delay::setPeriod (const double period) [inline]
Set the period.
Frequency gets set as well to 1 / period * 1000
Parameters:
period the period to be set
Definition at line 47 of file delay.h.
References _frequency, _period, and Constants::MILLISEC_PER_SECOND.
Referenced by DelayCalculator::process().
const double Delay::getPeriod () const [inline]
Get the period.
Returns:
the period
Definition at line 57 of file delay.h.
References _period.
Referenced by ZestMainWindow::updateView().
const double Delay::getFrenquency () const [inline]
Get the frenquency.
Returns:
the frenquency
Definition at line 63 of file delay.h.
References _frequency.
Referenced by ZestMainWindow::updateView().
Member Data Documentation
double Delay::_period [private]
the period of this delay
Definition at line 70 of file delay.h.
Referenced by getPeriod(), and setPeriod().
double Delay::_frequency [private]
the frequency corresponding to the period of this delay
Definition at line 73 of file delay.h.
Referenced by getFrenquency(), and setPeriod().
The documentation for this class was generated from the following files:
src/model/delay.h
src/model/delay.cpp