Zest Easy Studio Toolkit: TapTempoCalculator Class Reference
TapTempoCalculator Class Reference
#include <tapTempoCalculator.h>
Detailed Description
Calculate tempo from an average of several collected time intervals beetween quarter notes.
Implemented as a singleton.
Definition at line 34 of file tapTempoCalculator.h.
Public Member Functions
virtual void process ()
Collects timestamp and calculates tempo from previsouly gathered ones.
Static Public Member Functions
static TapTempoCalculator * getInstance ()
ceate and get the only instance.
static void destroy ()
Destroy the only instance.
Private Member Functions
TapTempoCalculator ()
virtual ~TapTempoCalculator ()
void initDeltas ()
init the list of deltas
double getAverageDelta () const
get the average delta from all deltas in list
bool getSteadiness () const
are deltas within a narrow range ?
Private Attributes
TimeStamper _timeStamper
provides timestamps on demand
list< int > _deltas
stores deltas between collected timestamps
Static Private Attributes
static const int DELTAS_COUNT = 3
We use 3 collected deltas to guess tempo.
static TapTempoCalculator * _instance = 0
The single instance.
Constructor & Destructor Documentation
TapTempoCalculator::TapTempoCalculator () [private]
init deltas collection with default data
Definition at line 39 of file tapTempoCalculator.cpp.
References initDeltas().
Referenced by getInstance().
TapTempoCalculator::~TapTempoCalculator () [private, virtual]
Definition at line 32 of file tapTempoCalculator.cpp.
Member Function Documentation
TapTempoCalculator * TapTempoCalculator::getInstance (void) [static]
ceate and get the only instance.
Returns:
the instance.
Definition at line 49 of file tapTempoCalculator.cpp.
References _instance, and TapTempoCalculator().
Referenced by ZestMainWindow::on_tapButton_pressed().
void TapTempoCalculator::destroy (void) [static]
Destroy the only instance.
Definition at line 61 of file tapTempoCalculator.cpp.
References _instance.
void TapTempoCalculator::process (void) [virtual]
Collects timestamp and calculates tempo from previsouly gathered ones.
Implements Processor.
Definition at line 77 of file tapTempoCalculator.cpp.
References _deltas, _timeStamper, getAverageDelta(), Document::getInstance(), TimeStamper::getStamp(), getSteadiness(), Constants::MILLISEC_PER_SECOND, Constants::SECONDS_PER_MINUTE, Document::setSteady(), Document::setTempo(), and Document::setTempoFromTap().
Referenced by ZestMainWindow::on_tapButton_pressed().
void TapTempoCalculator::initDeltas () [private]
init the list of deltas
Definition at line 112 of file tapTempoCalculator.cpp.
References _deltas, and DELTAS_COUNT.
Referenced by TapTempoCalculator().
double TapTempoCalculator::getAverageDelta () const [private]
get the average delta from all deltas in list
Returns:
the average of all deltas in list
Definition at line 122 of file tapTempoCalculator.cpp.
References _deltas, and DELTAS_COUNT.
Referenced by process().
bool TapTempoCalculator::getSteadiness () const [private]
are deltas within a narrow range ?
Returns:
a boolean describing steadiness
Definition at line 139 of file tapTempoCalculator.cpp.
References _deltas.
Referenced by process().
Member Data Documentation
const int TapTempoCalculator::DELTAS_COUNT = 3 [static, private]
We use 3 collected deltas to guess tempo.
Definition at line 43 of file tapTempoCalculator.h.
Referenced by getAverageDelta(), and initDeltas().
TapTempoCalculator * TapTempoCalculator::_instance = 0 [static, private]
The single instance.
Definition at line 62 of file tapTempoCalculator.h.
Referenced by destroy(), and getInstance().
TimeStamper TapTempoCalculator::_timeStamper [private]
provides timestamps on demand
Definition at line 121 of file tapTempoCalculator.h.
Referenced by process().
list<int> TapTempoCalculator::_deltas [private]
stores deltas between collected timestamps
Definition at line 124 of file tapTempoCalculator.h.
Referenced by getAverageDelta(), getSteadiness(), initDeltas(), and process().
The documentation for this class was generated from the following files:
src/process/tapTempoCalculator.h
src/process/tapTempoCalculator.cpp