Zest Easy Studio Toolkit: Observable Class Reference
Observable Class Reference
#include <observable.h>
Detailed Description
Observable design pattern abstract Class.
Definition at line 32 of file observable.h.
Public Member Functions
void registerObserver (Observer *observer)
Register a new observer.
void removeObserver (Observer *observer)
Remove a registered observer.
Protected Member Functions
Observable ()
virtual ~Observable ()
void notifyObservers () const
Notify all observers to update.
Private Attributes
vector< Observer * > _observers
collection of all observers
Constructor & Destructor Documentation
Observable::Observable () [protected]
Definition at line 28 of file observable.cpp.
Observable::~Observable () [protected, virtual]
Definition at line 34 of file observable.cpp.
Member Function Documentation
void Observable::registerObserver (Observer * observer)
Register a new observer.
Add observer to observers list
Parameters:
observer the observer to add
Definition at line 46 of file observable.cpp.
References _observers.
Referenced by ZestMainWindow::ZestMainWindow().
void Observable::removeObserver (Observer * observer)
Remove a registered observer.
Remove observer from observers list
Parameters:
observer the observer to remove
Definition at line 54 of file observable.cpp.
References _observers.
void Observable::notifyObservers () const [protected]
Notify all observers to update.
Notify all registered observers to update their view.
Definition at line 74 of file observable.cpp.
References _observers.
Referenced by Document::setMultiplier(), and Document::setTempo().
Member Data Documentation
vector<Observer*> Observable::_observers [private]
collection of all observers
Definition at line 78 of file observable.h.
Referenced by notifyObservers(), registerObserver(), and removeObserver().
The documentation for this class was generated from the following files:
src/dp/observable.h
src/dp/observable.cpp